
services:

  db:
    image: mysql:8.0.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./mysql-conf:/etc/mysql/mysql.conf.d
      - ./docker.cnf:/etc/mysql/conf.d
      - ./initPersistencia.sh:/docker-entrypoint-initdb.d/initPersistencia.sh
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - my-network
      
  md-backend-clean-flower:
    restart: on-failure
    container_name: md-backend-clean-flower
    build:
      context: ./clean-flower-back
      dockerfile: Dockerfile
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - my-network
      
  md-frontend-clean-flower:
    restart: on-failure
    container_name: md-frontend-clean-flower
    build:
      context: ./clean-flower-front
      dockerfile: Dockerfile
    expose:
      - 4200
    ports:
      - 4200:4200
    depends_on:
      - md-backend-clean-flower
    networks:
      - my-network

networks:
  my-network:
    driver: bridge 
